apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}-headless
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
  {{- with .Values.headlessService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  clusterIPs:
    - None
  internalTrafficPolicy: {{ .Values.service.internalTrafficPolicy }}
  ipFamilies: {{ .Values.service.ipFamilies | toYaml | nindent 4 }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  ports:
    - name: tcp-kafka-int
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: tcp-kafka-int
    - name: tcp-kafka-ctrl
      port: {{ .Values.service.controllerPort }}
      protocol: TCP
      targetPort: tcp-kafka-ctrl
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP 